Parameters of read_csv() in pandas

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name    Roll no     percentage            age  Number
0  yes          Neha Mohanta         49             85  not available       0
1  yes  Dibya Lochan Mohanta         65             87             18      11
2  yes  Jyotirmayee Mohanata         34  not available             24      22
3  yes                Laxman         23             45             67      22
4   No                 Arjun        NaN             22            NaN      34
5  yes                 Bheem        NaN             34            NaN      56
6  yes               Hanuman  no values             44             65      98
7  NaN            Ashwathama         23             55             67      89
8  yes             Rajashree         45            NaN             76      43

In [11]:
#How to handel null or missing valus
#NAN = Not a number 
#All these strings are considered as NAN valus by pandas
##N/A      -NaN        null
##N/A N/A  -nan        n/a
##NA       N/A         nan
#-1.#IND   NA          1.#IND
#-1.#QNAN  NULL        1.#QNAN
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',na_values = ['not available','no values'])
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0   NaN       0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0      11
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0      22
3  yes                Laxman     23.0        45.0  67.0      22
4   No                 Arjun      NaN        22.0   NaN      34
5  yes                 Bheem      NaN        34.0   NaN      56
6  yes               Hanuman      NaN        44.0  65.0      98
7  NaN            Ashwathama     23.0        55.0  67.0      89
8  yes             Rajashree     45.0         NaN  76.0      43

In [13]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',na_values = {'Roll no':'no values','percentage':'not available'})
df

  Data                  Name  Roll no  percentage            age  Number
0  yes          Neha Mohanta     49.0        85.0  not available       0
1  yes  Dibya Lochan Mohanta     65.0        87.0             18      11
2  yes  Jyotirmayee Mohanata     34.0         NaN             24      22
3  yes                Laxman     23.0        45.0             67      22
4   No                 Arjun      NaN        22.0            NaN      34
5  yes                 Bheem      NaN        34.0            NaN      56
6  yes               Hanuman      NaN        44.0             65      98
7  NaN            Ashwathama     23.0        55.0             67      89
8  yes             Rajashree     45.0         NaN             76      43

In [14]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',keep_default_na = False)
df

  Data                  Name    Roll no     percentage            age  Number
0  yes          Neha Mohanta         49             85  not available       0
1  yes  Dibya Lochan Mohanta         65             87             18      11
2  yes  Jyotirmayee Mohanata         34  not available             24      22
3  yes                Laxman         23             45             67      22
4   No                 Arjun       #N/A             22           null      34
5  yes                 Bheem       #N/A             34                     56
6  yes               Hanuman  no values             44             65      98
7                 Ashwathama         23             55             67      89
8  yes             Rajashree         45                            76      43

In [15]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',keep_default_na = True)
df

  Data                  Name    Roll no     percentage            age  Number
0  yes          Neha Mohanta         49             85  not available       0
1  yes  Dibya Lochan Mohanta         65             87             18      11
2  yes  Jyotirmayee Mohanata         34  not available             24      22
3  yes                Laxman         23             45             67      22
4   No                 Arjun        NaN             22            NaN      34
5  yes                 Bheem        NaN             34            NaN      56
6  yes               Hanuman  no values             44             65      98
7  NaN            Ashwathama         23             55             67      89
8  yes             Rajashree         45            NaN             76      43

In [17]:
#To find and interprete the missing values in a adata set
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',na_filter = False)
df

  Data                  Name    Roll no     percentage  age  Number
0  yes          Neha Mohanta         49             85   20      39
1  yes  Dibya Lochan Mohanta         65             87   18      11
2  yes  Jyotirmayee Mohanata         34  not available   24      22
3  yes                Laxman         23             45   67      22
4   No                 Arjun         25             22   45      34
5  yes                 Bheem         23             34   45      56
6  yes               Hanuman  no values             44   65      98
7   40            Ashwathama         23             55   67      89
8  yes             Rajashree         45             33   76      43