Handling Missing values
isnull()
notnull()

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4   No                 Arjun      NaN        22.0  45.0     NaN
5  yes                 Bheem      NaN        34.0  45.0     NaN
6  yes               Hanuman      NaN        44.0  65.0    98.0
7  NaN            Ashwathama     23.0        55.0   NaN    89.0
8  yes             Rajashree     45.0        33.0   NaN    43.0

In [6]:
df.isnull()

    Data   Name  Roll no  percentage    age  Number
0  False  False    False       False  False   False
1  False  False    False       False  False   False
2  False  False    False        True  False   False
3  False  False    False       False  False    True
4  False  False     True       False  False    True
5  False  False     True       False  False    True
6  False  False     True       False  False   False
7   True  False    False       False   True   False
8  False  False    False       False   True   False

In [ ]:
df.isnull().sum() # No. of Null valus in each column

Data          1
Name          0
Roll no       3
percentage    1
age           2
Number        3
dtype: int64

In [ ]:
df.isnull().sum().sum() #Total null values

np.int64(10)

In [10]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4   No                 Arjun      NaN        22.0  45.0     NaN
5  yes                 Bheem      NaN        34.0  45.0     NaN
6  yes               Hanuman      NaN        44.0  65.0    98.0
7  NaN            Ashwathama     23.0        55.0   NaN    89.0
8  yes             Rajashree     45.0        33.0   NaN    43.0

In [ ]:
df.notnull() #Opposite of isnull()

    Data  Name  Roll no  percentage    age  Number
0   True  True     True        True   True    True
1   True  True     True        True   True    True
2   True  True     True       False   True    True
3   True  True     True        True   True   False
4   True  True    False        True   True   False
5   True  True    False        True   True   False
6   True  True    False        True   True    True
7  False  True     True        True  False    True
8   True  True     True        True  False    True

In [12]:
df.notnull().sum()

Data          8
Name          9
Roll no       6
percentage    8
age           7
Number        6
dtype: int64

In [13]:
df.notnull().sum().sum()

np.int64(44)

In [21]:
#Series
import numpy as np
sr = pd.Series([1,2,3,4,np.nan,6,np.nan])
sr

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    NaN
dtype: float64

In [22]:
sr.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [23]:
sr.isnull().sum()

np.int64(2)

In [24]:
sr.notnull()

0     True
1     True
2     True
3     True
4    False
5     True
6    False
dtype: bool

In [25]:
sr.notnull().sum()

np.int64(5)

In [26]:
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4   No                 Arjun      NaN        22.0  45.0     NaN
5  yes                 Bheem      NaN        34.0  45.0     NaN
6  yes               Hanuman      NaN        44.0  65.0    98.0
7  NaN            Ashwathama     23.0        55.0   NaN    89.0
8  yes             Rajashree     45.0        33.0   NaN    43.0

In [27]:
#dropna() = it drops the rows or columns having NAN value and creates a new dataframe
df.dropna()

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0

In [ ]:
df.dropna(axis = 1) #Drops the columns having null value

                   Name
0          Neha Mohanta
1  Dibya Lochan Mohanta
2  Jyotirmayee Mohanata
3                Laxman
4                 Arjun
5                 Bheem
6               Hanuman
7            Ashwathama
8             Rajashree

In [30]:
df.dropna(how = 'any')

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0

In [ ]:
df.dropna(axis=1,how = 'any') #By default input of how is any and can choose all if all valus are null

                   Name
0          Neha Mohanta
1  Dibya Lochan Mohanta
2  Jyotirmayee Mohanata
3                Laxman
4                 Arjun
5                 Bheem
6               Hanuman
7            Ashwathama
8             Rajashree

In [34]:
df.dropna(how = 'all')

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4   No                 Arjun      NaN        22.0  45.0     NaN
5  yes                 Bheem      NaN        34.0  45.0     NaN
6  yes               Hanuman      NaN        44.0  65.0    98.0
7  NaN            Ashwathama     23.0        55.0   NaN    89.0
8  yes             Rajashree     45.0        33.0   NaN    43.0

In [37]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4  NaN                   NaN      NaN         NaN   NaN     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
6  NaN            Ashwathama     23.0        55.0   NaN    89.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [ ]:
df.dropna(how = 'all')#Drops the row or column i.e 4 if it's all values are null

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
6  NaN            Ashwathama     23.0        55.0   NaN    89.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [ ]:
df.dropna(thresh = 1) #prints if atlest one value is notnull

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
6  NaN            Ashwathama     23.0        55.0   NaN    89.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [41]:
df.dropna(thresh = 2)

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
6  NaN            Ashwathama     23.0        55.0   NaN    89.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [44]:
df.dropna(thresh = 5)

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [45]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
4  NaN                   NaN      NaN         NaN   NaN     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
6  NaN            Ashwathama     23.0        55.0   NaN    89.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [ ]:
df.dropna(subset = ['Data'])#Drops the rows corresponding to the given column containing NAN

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0
7  yes             Rajashree     45.0        33.0   NaN    43.0

In [48]:
df.dropna(subset = ['age'])

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0
2  yes  Jyotirmayee Mohanata     34.0         NaN  24.0    22.0
3  yes                Laxman     23.0        45.0  67.0     NaN
5  yes               Hanuman      NaN        44.0  65.0    98.0

In [ ]:
df.dropna(inplace = True) #We have to call df here 'inplace' as it doesnot create a new data frame .it just modifies the existing data frame
df

  Data                  Name  Roll no  percentage   age  Number
0  yes          Neha Mohanta     49.0        85.0  20.0    39.0
1  yes  Dibya Lochan Mohanta     65.0        87.0  18.0    11.0