##How To Write CSV Files In Pandas

In [52]:
import pandas as pd

In [53]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv') #dataset
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [54]:
type(df) #The csv file is in data frame format

pandas.core.frame.DataFrame

In [55]:
df.columns

Index(['Neha Mohanta', '49', '85', '20', '0'], dtype='object')

In [56]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',nrows = 1)
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11

In [57]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',nrows = 5)
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [58]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',usecols = [0])
df

           Neha Mohanta
0  Dibya Lochan Mohanta
1  Jyotirmayee Mohanata

In [59]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',usecols = [0,1])
df

           Neha Mohanta  49
0  Dibya Lochan Mohanta  65
1  Jyotirmayee Mohanata  34

In [60]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',usecols = [1,2,3,4])
df

   49  85  20   0
0  65  87  18  11
1  34  90  24  22

In [61]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [62]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',skiprows = 1)
df

   Dibya Lochan Mohanta  65  87  18  11
0  Jyotirmayee Mohanata  34  90  24  22

In [63]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',skiprows = 2)
df

Empty DataFrame
Columns: [Jyotirmayee Mohanata, 34, 90, 24, 22]
Index: []

In [64]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',skiprows = [0])
df

   Dibya Lochan Mohanta  65  87  18  11
0  Jyotirmayee Mohanata  34  90  24  22

In [65]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',skiprows = [2])
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11

In [66]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',skiprows = [1,2,3,4])
df

Empty DataFrame
Columns: [Neha Mohanta, 49, 85, 20, 0]
Index: []

In [67]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [69]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',index_col = '20')
df

            Neha Mohanta  49  85   0
20
18  Dibya Lochan Mohanta  65  87  11
24  Jyotirmayee Mohanata  34  90  22

In [ ]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',index_col = 1)
df

                          Name  Percentage  Age  Number
Roll No
49                Neha Mohanta          85   20       0
65        Dibya Lochan Mohanta          87   18      11
34        Jyotirmayee Mohanata          90   24      22

In [ ]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

                      0         1           2    3       4
0                  Name  Roll No   Percentage  Age  Number
1          Neha Mohanta        49          85   20       0
2  Dibya Lochan Mohanta        65          87   18      11
3  Jyotirmayee Mohanata        34          90   24      22

In [70]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',header = [1])
df

   Dibya Lochan Mohanta  65  87  18  11
0  Jyotirmayee Mohanata  34  90  24  22

In [71]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [72]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',header = [1])
df

   Dibya Lochan Mohanta  65  87  18  11
0  Jyotirmayee Mohanata  34  90  24  22

In [73]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

           Neha Mohanta  49  85  20   0
0  Dibya Lochan Mohanta  65  87  18  11
1  Jyotirmayee Mohanata  34  90  24  22

In [74]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',header = None)
df

                      0   1   2   3   4
0          Neha Mohanta  49  85  20   0
1  Dibya Lochan Mohanta  65  87  18  11
2  Jyotirmayee Mohanata  34  90  24  22

In [75]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',header = None, prefix = 'Columns')
df

TypeError: read_csv() got an unexpected keyword argument 'prefix'

In [80]:
df = df.add_prefix('Data')
df

,DataColColumnsColumns0,DataColColumnsColumns1,DataColColumnsColumns2,DataColColumnsColumns3,DataColColumnsColumns4
0,Neha Mohanta,49,85,20,0
1,Dibya Lochan Mohanta,65,87,18,11
2,Jyotirmayee Mohanata,34,90,24,22

In [82]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',names = ['a','b','c','d','e'])
df

                      a   b   c   d   e
0          Neha Mohanta  49  85  20   0
1  Dibya Lochan Mohanta  65  87  18  11
2  Jyotirmayee Mohanata  34  90  24  22

In [83]:
df =  pd.read_csv('C:/Users/DELL/Downloads/New.csv',names = ['Name','Roll NO','Percentage','Age','Number'])
df

                   Name  Roll NO  Percentage  Age  Number
0          Neha Mohanta       49          85   20       0
1  Dibya Lochan Mohanta       65          87   18      11
2  Jyotirmayee Mohanata       34          90   24      22