How To Create Python Pandas Dataframe

In [1]:
import pandas as pd

In [ ]:
#Creating an empty dataframe
#DataFrame method is used
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

In [4]:
lst = ['a','b','c']
print(lst)

['a', 'b', 'c']

In [7]:
df1 = pd.DataFrame(lst)
print(df1)

   0
0  a
1  b
2  c

In [8]:
df1

   0
0  a
1  b
2  c

In [9]:
ls_of_ls = [[1,2,3],[2,3,4],[4,5,6]]
print(ls_of_ls)

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [10]:
df2 = pd.DataFrame(ls_of_ls)
df2

   0  1  2
0  1  2  3
1  2  3  4
2  4  5  6

In [11]:
dict1 = {'ID':[11,22,33,44]}
dict1

{'ID': [11, 22, 33, 44]}

In [13]:
df3 = pd.DataFrame(dict1)
df3

   ID
0  11
1  22
2  33
3  44

In [ ]:
#ID is the label
dict1 = {'ID':[11,22,33,44],'SN':[1,2,3,4]} #The value of each data should be same

dict1

{'ID': [11, 22, 33, 44], 'SN': [1, 2, 3, 4]}

In [18]:
df3 = pd.DataFrame(dict1)
df3

   ID  SN
0  11   1
1  22   2
2  33   3
3  44   4

In [ ]:
ls_dict = [{'a':1,'b':2},{'a':3,'b':4}] #List of dictionaries
df5 = pd.DataFrame(ls_dict)
df5

   a  b
0  1  2
1  3  4

In [21]:
ls_dict = [{'a':1,'b':2},{'a':3,'b':4,'c':5}] #List of dictionaries
df5 = pd.DataFrame(ls_dict)
df5

   a  b    c
0  1  2  NaN
1  3  4  5.0

In [22]:
dict_sr = {'ID':pd.Series([1,2,3]), 'SN' : [111,222,333]}
df6 = pd.DataFrame(dict_sr)
df6

   ID   SN
0   1  111
1   2  222
2   3  333