Parameters of read_csv function in pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

                   Name  Roll no  percentage  age  Number
0          Neha Mohanta       49          85   20       0
1  Dibya Lochan Mohanta       65          87   18      11
2  Jyotirmayee Mohanata       34          90   24      22
3                Laxman       23          45   67      22
4                 Arjun       67          22   33      34
5                 Bheem       56          34   89      56
6               Hanuman       33          44   65      98
7            Ashwathama       23          55   67      89
8             Rajashree       45          45   76      43

In [3]:
df.head() #The head() method in pandas prints the first five rows

                   Name  Roll no  percentage  age  Number
0          Neha Mohanta       49          85   20       0
1  Dibya Lochan Mohanta       65          87   18      11
2  Jyotirmayee Mohanata       34          90   24      22
3                Laxman       23          45   67      22
4                 Arjun       67          22   33      34

In [4]:
df.head(1)

           Name  Roll no  percentage  age  Number
0  Neha Mohanta       49          85   20       0

In [6]:
df.head(8)

                   Name  Roll no  percentage  age  Number
0          Neha Mohanta       49          85   20       0
1  Dibya Lochan Mohanta       65          87   18      11
2  Jyotirmayee Mohanata       34          90   24      22
3                Laxman       23          45   67      22
4                 Arjun       67          22   33      34
5                 Bheem       56          34   89      56
6               Hanuman       33          44   65      98
7            Ashwathama       23          55   67      89

In [ ]:
#Head executes top methods 
df.tail() #Executed five rows from the bottom

         Name  Roll no  percentage  age  Number
4       Arjun       67          22   33      34
5       Bheem       56          34   89      56
6     Hanuman       33          44   65      98
7  Ashwathama       23          55   67      89
8   Rajashree       45          45   76      43

In [8]:
df.tail(2)

         Name  Roll no  percentage  age  Number
7  Ashwathama       23          55   67      89
8   Rajashree       45          45   76      43

In [9]:
df.tail(7)

                   Name  Roll no  percentage  age  Number
2  Jyotirmayee Mohanata       34          90   24      22
3                Laxman       23          45   67      22
4                 Arjun       67          22   33      34
5                 Bheem       56          34   89      56
6               Hanuman       33          44   65      98
7            Ashwathama       23          55   67      89
8             Rajashree       45          45   76      43

In [12]:
#tail() method quicklu verifies the data set in pandas
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',dtype = {'percentage':'float64'})
df

                   Name  Roll no  percentage  age  Number
0          Neha Mohanta       49        85.0   20       0
1  Dibya Lochan Mohanta       65        87.0   18      11
2  Jyotirmayee Mohanata       34        90.0   24      22
3                Laxman       23        45.0   67      22
4                 Arjun       67        22.0   33      34
5                 Bheem       56        34.0   89      56
6               Hanuman       33        44.0   65      98
7            Ashwathama       23        55.0   67      89
8             Rajashree       45        45.0   76      43

In [13]:
#true_value is used to change the 'yes' if present at any data set to string
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv')
df

  Data                  Name  Roll no  percentage  age  Number
0  yes          Neha Mohanta       49          85   20       0
1  yes  Dibya Lochan Mohanta       65          87   18      11
2  yes  Jyotirmayee Mohanata       34          90   24      22
3  yes                Laxman       23          45   67      22
4  yes                 Arjun       67          22   33      34
5  yes                 Bheem       56          34   89      56
6  yes               Hanuman       33          44   65      98
7  yes            Ashwathama       23          55   67      89
8  yes             Rajashree       45          45   76      43

In [19]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',true_values = ['yes']) #We can change any string as true
df

  Data                  Name  Roll no  percentage  age  Number
0  yes          Neha Mohanta       49          85   20       0
1  yes  Dibya Lochan Mohanta       65          87   18      11
2  yes  Jyotirmayee Mohanata       34          90   24      22
3  yes                Laxman       23          45   67      22
4   No                 Arjun       67          22   33      34
5  yes                 Bheem       56          34   89      56
6  yes               Hanuman       33          44   65      98
7  yes            Ashwathama       23          55   67      89
8  yes             Rajashree       45          45   76      43

In [18]:
df = pd.read_csv('C:/Users/DELL/Downloads/New.csv',true_values = ['yes'],false_values =['No'] )
df

    Data                  Name  Roll no  percentage  age  Number
0   True          Neha Mohanta       49          85   20       0
1   True  Dibya Lochan Mohanta       65          87   18      11
2   True  Jyotirmayee Mohanata       34          90   24      22
3   True                Laxman       23          45   67      22
4  False                 Arjun       67          22   33      34
5   True                 Bheem       56          34   89      56
6   True               Hanuman       33          44   65      98
7   True            Ashwathama       23          55   67      89
8   True             Rajashree       45          45   76      43